name: Documentation

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: rustup show
      - uses: Swatinem/rust-cache@v2
      - name: Generate Base documentation
        run: cargo run -p nash-cli -- docs --base --out target/base-docs
      - name: Save documentation preview
        uses: actions/upload-artifact@v4
        with:
          name: base-documentation
          path: target/base-docs
